version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: user.root
      MYSQL_DATABASE: easycert
      MYSQL_USER: user
      MYSQL_PASSWORD: user.root*
    ports:
      - "8080:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - mynetwork
    depends_on:
      - mysql

networks:
  mynetwork:
